### ISSUE TITLE
Logo licensing

### ISSUE THREAD

**Issue by hofmannsven** [sebastianheuer/phpunit-logo#6]
I'd like to start a discussion about a suitable license for a logo and also the font of the logo (if there is one). I feel like a license should be in place right from the start.

Reference: [PHP logo licensing](http://php.net/download-logos.php)

**Comment by belanur** [comment]
Very good point! I would like to add Sebastian Bergmann to the discussion

**Comment by sebastianbergmann** [comment]
The PHP logo licensing looks reasonable to me.

**Comment by kelunik** [comment]
You will also need to cover the licensing from the creator to PHPUnit / @sebastianbergmann. If an entity other than the creator wants to file lawsuits, that entity needs an exclusive license, at least in Germany.

**Comment by sebastianbergmann** [comment]
@kelunik Good point. Here's hoping there's a standard contract for this somewhere on the Internet.

**Comment by kelunik** [comment]
@sebastianbergmann I haven't found something for @amphp yet. The issue is mainly that all existing things assume there's a legal entity that can own that right. It might be fine for PHPUnit if you own it alone, but it doesn't work with multiple main maintainers.

**Comment by sebastianbergmann** [comment]
I think so, too. The creator of the logo needs to give me an exclusive license for the logo.

**Comment by belanur** [comment]
This should be reflected in README.md, so everyone submitting ideas will be aware of that even before we have a proper license in place .

**Comment by theseer** [comment]
FWIW: In case my logo suggenstion wins, I don't have an issues waving a rights I can legally wave and pass them on to Sebastian.

IANAL, but unless you want to release the SVG version with actual text rather then vector lines, no font license is needed if the author/designer had a valid license. The fonts i used are either open source or i own a license.
